### PR TITLE
Add R7RS shim

### PR DESCRIPTION
**Pull request by lassik**
@mnieper Is this correct?

cc @jpellegrini, ref https://github.com/egallesio/STklos/pull/444

### CODE REVIEW

**Comment by mnieper** [comment]
Why would you want to use this library on an R7RS system?

**Comment by jpellegrini** [comment]
> Why would you want to use this library on an R7RS system?

Not really "using the implementation", but "declaring support for the SRFI", which is basically `define-values` anyway.

**Comment by jpellegrini** [comment]
Or, since the SRFI defines a library, maybe an R7RS system should create a library that just re-exports the syntax (just for compatibility) (?)

**Comment by mnieper** [comment]
> > Why would you want to use this library on an R7RS system?
> 
> Not really "using the implementation", but "declaring support for the SRFI", which is basically `define-values` anyway.

As this SRFI only prescribes a library for R6RS systems, an R7RS implementation can declare support of SRFI 244 (if it must  so) without providing any library.

For compatibility, `(srfi 244)` is useless.

**Comment by jpellegrini** [comment]
> an R7RS implementation can declare support of SRFI 244 (if it must so) without providing any library.

Thanks - that's what I thought. My PR for STklos only added the SRFI to the supported list.

**Comment by lassik** [comment]
A SRFI sample implementation is not necessarily useful. It may just showcase different ways to implement the spec correctly, for pedagogical value. See e.g. the [null implementation of SRFI 238](https://github.com/scheme-requests-for-implementation/srfi-238/tree/master/impl-null).

**Comment by mnieper** [comment]
I don't even see any pedagogical value in providing a trivial implementation of some library name `(srfi 244)`.  In fact, I see it as counterproductive as it obscures the fact that there is never a reason to actually import such a library.

**Comment by lassik** [comment]
Fair enough. I don't have time to present more arguments.

**Comment by egallesio** [comment]
> Why would you want to use this library on an R7RS system?

In fact, you may want to have access to define-values in a context which is not fully R7RS on a R7RS system. Something like 

```scheme
(define-library (foo)
  (import (scheme r5rs)
          (srfi 244))
  (begin
    (define-values (a b) (values 1 2))
    (display (cons b a))))
```

**Comment by mnieper** [comment]
In that case, you can do `(import (only (scheme base) define-values))`.  If `(scheme base)` does not define `define-values`, the trivial implementation of `(srfi 244)` cannot be used anyway.

IMHO, if any other implementation of SRFI 244 besides the R6RS one makes sense, then for R5RS systems (that don't have `define-values`). But for these systems, it has to be packaged as a file that can be loaded and not as a library.

**Comment by egallesio** [comment]
You are right, `(import (only (scheme base) define-values))` is a possible solution. I should have seen it.

**Pull request closed without merging**
